### PR TITLE
BIGTOP-4246: Refactor APIs for Cluster

### PR DESCRIPTION
**Pull request by kevinw66**

### CODE REVIEW

**Comment by kevinw66** [comment]
The command for cluster will be adjusted in future PRs

**Comment by MacChen01** [comment]
+1 lgtm

**Review by wuchunfu — APPROVED** [review]
It looks good overall, but can you show a screenshot of your run?

**Comment by kevinw66** [comment]
> It looks good overall, but can you show a screenshot of your run?

Hi, this is only API changes, here is the screenshot of testing results on Postman
image

**Review by wuchunfu — APPROVED** [review]
LGTM

**Comment by kevinw66** [comment]
Thanks @MacChen01 @wuchunfu

**Pull request merged**
